.env
README.md
config/conn.js
controllers/Brand.js
controllers/Cart.js
controllers/Category.js
controllers/Order.js
controllers/Product.js
controllers/User.js
models/Brand.js
models/Cart.js
models/Category.js
models/Order.js
models/Product.js
models/User.js
package-lock.json
package.json
routes/router.js
server.js

update Code 

---

server.js

This fixes issue Product router in server.js 
fixes #32 
- Bug fix

 fix: product router

---

server.js

This PR implements category router in server.js 
fixes #34
- Feature implementation
- [ X] Go to server.js
- [ X] Check the category router middleware

feat: category router feature implemented

---

server.js

This fixes issue cart router in server.js 
fixes #33 
- Bug fix

fix: Fix/cart router

---

models/Product.js

documentation has been written for product model
fixes #39 
- docs

docs: product model documentation Product.js

---

models/Product.js

Product model export bug has been resolved.
fixes #41 
- Bug fix

fix: product model export 

---

models/Category.js

Category model export has been fixed
fixes #42 
- Bug fix

fix: Catgeory model export fixed

---

models/Brand.js

This fixes issue of brand model export
fixes #43 
- Bug fix

fix: Brand model export

---

models/User.js

This fixes issue user model export
fixes #31 
- Bug fix

fix: User model export

---

controllers/Product.js

This fixes issue Product model import
fixes #45 
- Bug fix

fix: Product model import resolved

---

models/Product.js

fix: product model export

---

models/Order.js

This fixes order model export
fixes #28

fix: update order model export

---

models/Category.js

This fixes  Category model export 
fixes #26

fix: Category model export updated

---

controllers/Order.js

This fixes order model import in order controller
fixes #25

fix: order model import in order controller

---

controllers/Product.js

this fixes product import
fixes #24

fix: product model import

---

controllers/Category.js

This fixes category model import in category controller.
fixes #23

fix: category model import

---

controllers/Brand.js

This fixes brand model import in brand controller
fixes #22

fix: brand model import

---

controllers/Cart.js

This fixes cart model import in cart controller
fixes #21

fix: cart model import

---

controllers/User.js

This fixes user model import in user controller
fixes #20

fix: user model import

---

controllers/User.js

This fixes auth model import
fixes #19

fix: auth model import

---

models/User.js

This fixes auth model
fixes #18

fix: auth model updated

---

models/Category.js

This fixes category model.
fixes #17

fix: category model updated

---

models/Brand.js

This fixes brand model
fixes #16

fix: brand model

---

models/Product.js

This fixes product model
fixes #15

fix: product model

---

routes/User.js

separate file created is created for user routes
fixes #11

feat: separate file created for user routes

---

routes/router.js

This fixes user routes has been un-commented in routes.js
fixes #68

feat: docs: user routes un-commented

---

models/Order.js

This fixes order model
fixes #14

fix: order model fixed

---

models/Cart.js

This fixes cart model
fixes #13

fix: cart model fixed

---

models/User.js

This fixes user model
fixes #12

fix: user model fixed

---

routes/Product.js

This fixes separate product route file
fixes #10

fix: separate product route file

---

routes/Order.js

This fixes Separate route file for order
fixes #9

feat: docs: Separate route file for order

---

routes/router.js

This fixes unneccessary routes
fixes #77

fix: unneccessary routes

---

routes/Category.js

This PR enhances new feature category router file for category routes to make code more cleaner.
fixes #8

feat: Separate router file for category

---

routes/Brand.js

This fixes separate route file for brand
fixes #7

feat: separate route file for brand

---

routes/User.js

This fixes separate router file for user created
fixes #5

feat: Separate router file for user created
